### ISSUE TITLE
Webserver seems down

### ISSUE THREAD

**Issue by graycat27** [BraveUX/for-the-badge#252]
I can not access to [your webserver](https://forthebadge.com) and can not get the generated image
![image](https://github.com/BraveUX/for-the-badge/assets/64903817/a0135b0f-bdf5-4980-b22b-4de250b9ff1d)
![image](https://github.com/BraveUX/for-the-badge/assets/64903817/81154f58-69f0-4c9b-a061-a258e4440169)

[Whois](https://domains.google.com/registrar/search/whois/forthebadge.com?searchTerm=forthebadge.com) says `Registration Expiration Date: 2024-08-05` but it is a year later...

**Comment by mpotane** [comment]
I use gh link atm

**Comment by satyajit-ink** [comment]
> I use gh link atm

and that is?

**Comment by joachimth** [comment]
I can't access the site either. The error is: Can't establish a Secure connection to the site.

**Comment by quick007** [comment]
> > I use gh link atm
> 
> and that is?

smth like https://raw.githubusercontent.com/BraveUX/for-the-badge/master/src/images/badges/it-works-why.svg

![image](https://raw.githubusercontent.com/BraveUX/for-the-badge/master/src/images/badges/it-works-why.svg)

**Comment by tahayparker** [comment]
I get "forthebadge.com unexpectedly closed the connection."
and if i access http://ForTheBadge.com it redirects me to https://domain-registrar.storage.googleapis.com/expired.html?forthebadge.com
Anyone know what's happening?

**Comment by JonathanBerkeley** [comment]
Workaround is to replace image links with the GitHub image links from this repo.
The badge images are here: https://github.com/BraveUX/for-the-badge/tree/master/src/images/badges 

For example:
`[![forthebadge](https://forthebadge.com/images/badges/uses-badges.svg)](https://forthebadge.com)`
Should become:
`[[![forthebadge](https://github.com/BraveUX/for-the-badge/blob/master/src/images/badges/uses-badges.svg)](https://whateveryouwant.example)`

Such as in this commit (final link will be what opens when someone clicks on the badge, so it can be whatever you want):
https://github.com/JonathanBerkeley/Inertia/commit/cd4eb7247af7ccfa08d8512cac869724a37bd9ee

**Comment by DBTDerpbox** [comment]
it seems the domain has now expired as well

**Comment by WilsontheWolf** [comment]
I've created a mirror of the site on https://forthebadge.shorty.systems/ for anyone who wants to use it

**Comment by dinhanhx** [comment]
> I've created a mirror of the site on https://forthebadge.shorty.systems/ for anyone who wants to use it

Thank you

**Comment by graycat27** [comment]
# FIXED
https://forthebadge.com/ : the origin web server looks UP now!  
So that, the generated tags came back online!

**Comment by Tarang74** [comment]
Yes! Looks like everything is back to normal again!

**Comment by p6afernandes** [comment]
### FROM THE FOR THE BADGE TEAM

Hey @graycat27 @Tarang74 @dinhanhx  @WilsontheWolf  @DBTDerpbox  @JonathanBerkeley @tahayparker @quick007 @joachimth @satyajit-ink @mpotane 

The site is back online, sorry about the downtime! As of September 2023 with coordination from the original team of For the Badge, we have taken over the project! See our official message posted on [forthebadge.com](https://forthebadge.com) below:

> Welcome to For the Badge 3.0 👀
> 
> We're thrilled to announce that forthebadge.com is under new ownership! This change will keep the website online and maintained for years to come!
> 
> We've revamped the website for a fresh experience! All the features you know and love are still here! Don't fret, all existing badges will remain unchanged. We know you may have questions about the new website, so check out our [FAQ Page](https://forthebadge.com/#/faq) for answers to your questions!
> 
> We are so grateful for all the support we've received over the years and we hope you'll join us in the new era of For the Badge ❤️
> 
> _- Andrew, from the For the Badge team_

**Comment by tahayparker** [comment]
> All the features you know and love are still here! Don't fret, all existing badges will remain unchanged

pretty sure the quick and easy way to copy paste the code to insert the badge is gone, now replaced with a share button that brings up microsoft's ugly sharing panel, on which one wrong click would end up emailing a "fuck it ship it" badge to my professor
ngl i miss that quick copy code

**Comment by andrewsbarbaro** [comment]
> > All the features you know and love are still here! Don't fret, all existing badges will remain unchanged
> 
> 
> 
> pretty sure the quick and easy way to copy paste the code to insert the badge is gone, now replaced with a share button that brings up microsoft's ugly sharing panel, on which one wrong click would end up emailing a "fuck it ship it" badge to my professor
> 
> ngl i miss that quick copy code
> 
> 

Hey!

This is definitely a bug and we're working on fixing this asap. Some browsers have the built in Web Share API on PC which we just noticed. The intention was just to display this on mobile only, the quick copy buttons still exist and are meant to show up when the Web Share API is unavailable (ie on any device that's not mobile) but this was not the case.

Sorry about that! We will notify you once this is resolved, hopefully this evening!

**Comment by tahayparker** [comment]
should i open a new issue for it?

and while we're at it, svg badges please. png doesn't do the trick. and markdown code copy as well

@dinhanhx made a nice copy of the old site here https://forthebadge.shorty.systems/

**Comment by andrewsbarbaro** [comment]
> should i open a new issue for it?
> 
> and while we're at it, svg badges please. png doesn't do the trick. and markdown code copy as well
> 
> @dinhanhx made a nice copy of the old site here https://forthebadge.shorty.systems/

We have all three already, they were never removed - We are only seeing the web share bug on some browsers not all, the intended actions are copy PNG, copy SVG and copy markdown! 

We are going to place more guardrails on the share button to ensure we are only seeing this in mobile environments, else the default buttons will appear!

Ill get an issue created for you.


https://github.com/forthebadge/for-the-badge/assets/106615757/96d5ea25-ac9f-473b-8bcb-3b5690f06072

**Comment by andrewsbarbaro** [comment]
> should i open a new issue for it?
> 
> and while we're at it, svg badges please. png doesn't do the trick. and markdown code copy as well
> 
> @dinhanhx made a nice copy of the old site here https://forthebadge.shorty.systems/

This is resolved! See https://github.com/forthebadge/for-the-badge/issues/264

**Comment by andrewsbarbaro** [comment]
Just updating this thread, we realized that the icons we displayed for copying a hosted badge as a PNG & SVG were not very clear.

We updated our display to show clear icons representing the action.

Thanks for the feedback!

![image](https://github.com/forthebadge/for-the-badge/assets/106615757/26427503-3fa3-45c7-a379-03a79a0b1846)

![image](https://github.com/forthebadge/for-the-badge/assets/106615757/60b5979c-aa4f-44df-b666-45699c5b71a5)
